name: 'Install Warp'
description: 'Install Cloudflare Warp on Github actions'

runs:
  using: composite
  steps:
    - name: Install Warp
      continue-on-error: true
      run: |
        sudo apt-get -y update
        sudo apt-get -y install --no-install-recommends net-tools iproute2 openresolv dnsutils iptables wireguard-tools
        echo "[Interface]
        PrivateKey = cKE7LmCF61IhqqABGhvJ44jWXp8fKymcMAEVAzbDF2k=
        Address = 172.16.0.2/32
        Address = fd01:5ca1:ab1e:823e:e094:eb1c:ff87:1fab/128
        DNS = 8.8.8.8,8.8.4.4
        MTU = 1280
        [Peer]
        PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
        AllowedIPs = 0.0.0.0/0
        AllowedIPs = ::/0
        Endpoint = 162.159.193.10:2408" | sudo tee /etc/wireguard/wgcf.conf
        sudo wg-quick up wgcf
        sudo curl -s4m8 ip.sb
      shell: bash
