name: WARP Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run WARP Script
        run: |
          chmod +x warp.sh
          ./warp.sh

      - name: Upload WireGuard config
        uses: actions/upload-artifact@v4
        with:
          name: wireguard-warp
          path: output/wireguard-warp.conf
