name: WARP Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download and run warp.sh
        run: |
          curl -Lo warp.sh https://raw.githubusercontent.com/8moonman8/warp-on-actions/main/warp.sh
          chmod +x warp.sh
          ./warp.sh

      - name: Upload config
        uses: actions/upload-artifact@v4
        with:
          name: wireguard-warp
          path: output/wireguard-warp.conf

