name: WARP-On-Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Run WARP script
        run: |
          curl -sSL https://raw.githubusercontent.com/fscarmen/warp-on-actions/main/warp.sh | bash

