name: WARP-On-Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run original WARP script
        run: |
          curl -sSL https://raw.githubusercontent.com/fscarmen/warp-on-actions/main/warp.sh | bash
