name: WARP-On-Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run WARP script from alternative repo
        run: |
          curl -sSL https://raw.githubusercontent.com/its-pointless/warp-on-actions/main/warp.sh | bash

